// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistance;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230707203857_MigrationToPostgresql")]
    partial class MigrationToPostgresql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.ActorShowRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasColumnType("text");

                    b.Property<double>("Pay")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("RoleId")
                        .IsUnique();

                    b.HasIndex("ShowId");

                    b.ToTable("ActorShowRoles");
                });

            modelBuilder.Entity("Domain.ActorShowRoleAudition", b =>
                {
                    b.Property<string>("ActorId")
                        .HasColumnType("text");

                    b.Property<Guid>("AuditionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShowRoleId")
                        .HasColumnType("uuid");

                    b.HasKey("ActorId", "AuditionId", "ShowRoleId");

                    b.HasIndex("AuditionId")
                        .IsUnique();

                    b.HasIndex("ShowRoleId");

                    b.ToTable("ActorShowRoleAuditions");
                });

            modelBuilder.Entity("Domain.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Audition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("VideoURL")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Auditions");
                });

            modelBuilder.Entity("Domain.AuditionReview", b =>
                {
                    b.Property<Guid>("AuditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewerId")
                        .HasColumnType("text");

                    b.Property<double>("Review")
                        .HasColumnType("double precision");

                    b.HasKey("AuditionId", "ReviewerId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("AuditionReviews");
                });

            modelBuilder.Entity("Domain.Festival", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ZipCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Festivals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a553b5f9-220c-4f45-91e5-9419f7baf575"),
                            City = "Beograd",
                            EndDate = new DateTime(2023, 9, 7, 20, 38, 57, 752, DateTimeKind.Utc).AddTicks(4166),
                            Name = "Festival 1",
                            StartDate = new DateTime(2023, 8, 7, 20, 38, 57, 752, DateTimeKind.Utc).AddTicks(4160),
                            ZipCode = 36300
                        },
                        new
                        {
                            Id = new Guid("296074d9-28f6-4beb-bb23-9490e1e0ab6c"),
                            City = "Beograd",
                            EndDate = new DateTime(2023, 11, 7, 20, 38, 57, 752, DateTimeKind.Utc).AddTicks(4175),
                            Name = "Festival 2",
                            StartDate = new DateTime(2023, 10, 7, 20, 38, 57, 752, DateTimeKind.Utc).AddTicks(4174),
                            ZipCode = 36300
                        },
                        new
                        {
                            Id = new Guid("629bd6d5-be2b-4348-bdbf-34d3af7f8de7"),
                            City = "Beograd",
                            EndDate = new DateTime(2024, 1, 7, 20, 38, 57, 752, DateTimeKind.Utc).AddTicks(4181),
                            Name = "Festival 3",
                            StartDate = new DateTime(2023, 12, 7, 20, 38, 57, 752, DateTimeKind.Utc).AddTicks(4181),
                            ZipCode = 36300
                        },
                        new
                        {
                            Id = new Guid("926a6755-ce4b-40a6-a2b3-5d667db816aa"),
                            City = "Beograd",
                            EndDate = new DateTime(2024, 3, 7, 20, 38, 57, 752, DateTimeKind.Utc).AddTicks(4188),
                            Name = "Festival 4",
                            StartDate = new DateTime(2024, 2, 7, 20, 38, 57, 752, DateTimeKind.Utc).AddTicks(4188),
                            ZipCode = 36300
                        },
                        new
                        {
                            Id = new Guid("4506a2e2-17d2-46e2-96ea-3f6ff42831b2"),
                            City = "Beograd",
                            EndDate = new DateTime(2024, 5, 7, 20, 38, 57, 752, DateTimeKind.Utc).AddTicks(4196),
                            Name = "Festival 5",
                            StartDate = new DateTime(2024, 4, 7, 20, 38, 57, 752, DateTimeKind.Utc).AddTicks(4194),
                            ZipCode = 36300
                        });
                });

            modelBuilder.Entity("Domain.Photo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Domain.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Domain.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("uuid");

                    b.Property<int>("LengthOfPlay")
                        .HasColumnType("integer");

                    b.Property<Guid>("TheatreShowScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TimeOfPlay")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FestivalId");

                    b.HasIndex("TheatreShowScheduleId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Domain.Show", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("text");

                    b.Property<string>("DirectorName")
                        .HasColumnType("text");

                    b.Property<int>("LengthOfPlay")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("integer");

                    b.Property<string>("StoryWriterName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("Domain.ShowFestivalApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumberOfActors")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TheatreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FestivalId");

                    b.HasIndex("ShowId");

                    b.HasIndex("TheatreId");

                    b.ToTable("ShowFestivalApplications");
                });

            modelBuilder.Entity("Domain.ShowFestivalApplicationReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Acceptable")
                        .HasColumnType("boolean");

                    b.Property<string>("ReviewerId")
                        .HasColumnType("text");

                    b.Property<Guid>("ShowFestivalApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("ShowFestivalApplicationId");

                    b.HasIndex("ShowId");

                    b.ToTable("ShowFestivalApplicationReviews");
                });

            modelBuilder.Entity("Domain.ShowRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ShowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShowId");

                    b.ToTable("ShowRoles");
                });

            modelBuilder.Entity("Domain.Theatre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ManagerId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("YearOfCreation")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique();

                    b.ToTable("Theatres");
                });

            modelBuilder.Entity("Domain.TheatreShow", b =>
                {
                    b.Property<Guid>("TheatreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumberOfActors")
                        .HasColumnType("integer");

                    b.HasKey("TheatreId", "ShowId");

                    b.HasIndex("ShowId");

                    b.ToTable("TheatreShows");
                });

            modelBuilder.Entity("Domain.TheatreShowSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TheatreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShowId");

                    b.HasIndex("TheatreId");

                    b.ToTable("TheatreShowSchedules");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.ActorShowRole", b =>
                {
                    b.HasOne("Domain.AppUser", "Actor")
                        .WithMany("ActingRoles")
                        .HasForeignKey("ActorId");

                    b.HasOne("Domain.ShowRole", "Role")
                        .WithOne("PickedActor")
                        .HasForeignKey("Domain.ActorShowRole", "RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Show", "Show")
                        .WithMany("Actors")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Role");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Domain.ActorShowRoleAudition", b =>
                {
                    b.HasOne("Domain.AppUser", "Actor")
                        .WithMany("Auditions")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Audition", "Audition")
                        .WithOne("ActorShowRole")
                        .HasForeignKey("Domain.ActorShowRoleAudition", "AuditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ShowRole", "ShowRole")
                        .WithMany("ShowRoleAuditions")
                        .HasForeignKey("ShowRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Audition");

                    b.Navigation("ShowRole");
                });

            modelBuilder.Entity("Domain.AuditionReview", b =>
                {
                    b.HasOne("Domain.Audition", "Audition")
                        .WithMany("Reviews")
                        .HasForeignKey("AuditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AppUser", "Reviewer")
                        .WithMany("AuditionReviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audition");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Domain.Festival", b =>
                {
                    b.HasOne("Domain.Theatre", "Organizer")
                        .WithMany("FestivalsOrganized")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Domain.Photo", b =>
                {
                    b.HasOne("Domain.AppUser", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.RefreshToken", b =>
                {
                    b.HasOne("Domain.AppUser", "AppUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Domain.Schedule", b =>
                {
                    b.HasOne("Domain.Festival", "Festival")
                        .WithMany("ShowSchedules")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.TheatreShowSchedule", "TheatreShow")
                        .WithMany("Schedules")
                        .HasForeignKey("TheatreShowScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festival");

                    b.Navigation("TheatreShow");
                });

            modelBuilder.Entity("Domain.ShowFestivalApplication", b =>
                {
                    b.HasOne("Domain.Festival", "Festival")
                        .WithMany("ShowApplications")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Show", "Show")
                        .WithMany("Applications")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Theatre", "Theatre")
                        .WithMany()
                        .HasForeignKey("TheatreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festival");

                    b.Navigation("Show");

                    b.Navigation("Theatre");
                });

            modelBuilder.Entity("Domain.ShowFestivalApplicationReview", b =>
                {
                    b.HasOne("Domain.AppUser", "Reviewer")
                        .WithMany("ShowApplications")
                        .HasForeignKey("ReviewerId");

                    b.HasOne("Domain.ShowFestivalApplication", "Application")
                        .WithMany("Reviews")
                        .HasForeignKey("ShowFestivalApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Show", null)
                        .WithMany("ApplicationReviews")
                        .HasForeignKey("ShowId");

                    b.Navigation("Application");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Domain.ShowRole", b =>
                {
                    b.HasOne("Domain.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Domain.Theatre", b =>
                {
                    b.HasOne("Domain.AppUser", "Manager")
                        .WithOne("ManagedTheatre")
                        .HasForeignKey("Domain.Theatre", "ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Domain.TheatreShow", b =>
                {
                    b.HasOne("Domain.Show", "Show")
                        .WithMany("Theatres")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Theatre", "Theatre")
                        .WithMany("Shows")
                        .HasForeignKey("TheatreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");

                    b.Navigation("Theatre");
                });

            modelBuilder.Entity("Domain.TheatreShowSchedule", b =>
                {
                    b.HasOne("Domain.Show", "Show")
                        .WithMany("TheatreSchedules")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Theatre", "Theatre")
                        .WithMany("ShowSchedules")
                        .HasForeignKey("TheatreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");

                    b.Navigation("Theatre");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.AppUser", b =>
                {
                    b.Navigation("ActingRoles");

                    b.Navigation("AuditionReviews");

                    b.Navigation("Auditions");

                    b.Navigation("ManagedTheatre");

                    b.Navigation("Photos");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ShowApplications");
                });

            modelBuilder.Entity("Domain.Audition", b =>
                {
                    b.Navigation("ActorShowRole");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.Festival", b =>
                {
                    b.Navigation("ShowApplications");

                    b.Navigation("ShowSchedules");
                });

            modelBuilder.Entity("Domain.Show", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("ApplicationReviews");

                    b.Navigation("Applications");

                    b.Navigation("TheatreSchedules");

                    b.Navigation("Theatres");
                });

            modelBuilder.Entity("Domain.ShowFestivalApplication", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.ShowRole", b =>
                {
                    b.Navigation("PickedActor");

                    b.Navigation("ShowRoleAuditions");
                });

            modelBuilder.Entity("Domain.Theatre", b =>
                {
                    b.Navigation("FestivalsOrganized");

                    b.Navigation("ShowSchedules");

                    b.Navigation("Shows");
                });

            modelBuilder.Entity("Domain.TheatreShowSchedule", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
